# Generated by Django 4.2.4 on 2023-09-13 01:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('QRScanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
